apiVersion: v1
data:
  consul_address: "service-discovery-center.infra.svc.cluster.local"
  consul_port: "8500"
  consul_scheme: "http"
  consul_ca_file: ""
  consul_cert_file: ""
  consul_key_file: ""
  consul_insecure_skip_verify: "false"
  consul_token: ""
  consul_timeout: "2s"
  consul_container_name: "consul"
  consul_node_selector: "consul=enabled"
  pod_label_selector: ""
  k8s_tag: "kubernetes"
  register_mode: "node"
  register_source: "service"
kind: ConfigMap
metadata:
  name: kube-consul-register
  namespace: infra

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-consul-register
  name: kube-consul-register
  namespace: infra
spec:
  selector:
    matchLabels:
      app: kube-consul-register
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-consul-register
    spec:
      containers:
      - name: kube-consul-register
        args:
        - -logtostderr=true
        - -configmap=infra/kube-consul-register
        - -in-cluster=true
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: registry.stardream.link/warjiang/kube-consul-register:canary
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 1
            memory: 300Mi
        volumeMounts:
          - name: tz-config
            mountPath: /etc/localtime
      imagePullSecrets:
       - name: stardreamkey
      volumes:
        - name: tz-config
          hostPath:
            path: /etc/localtime

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    consul.register/service.health.path: /v1/status/leader
    consul.register/service.name: vpc.common.sdc
  name: service-discovery-center
  namespace: infra
spec:
  ports:
  - port: 8500
    protocol: TCP
    targetPort: 8500
  selector:
    component: client
  type: ClusterIP

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: infra
  name: configmap-reader
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-configmaps
  namespace: infra
subjects:
- kind: ServiceAccount
  name: default
  namespace: infra
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consul-register-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - services
  - nodes
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consul-register-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: consul-register-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:serviceaccount:infra:default