name: Push released image

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  build:
    name: Build and push image
    if: ${{ github.repository == 'warjiang/kube-consul-register' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Package
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: $GITHUB_ACTOR
          password: ${{secrets.GH_TOKEN}}

      - name: Build docker image and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: |
            linux/amd64,
            linux/arm64
          push: true
          tags: |
            warjiang/kube-consul-register:${{ github.ref_name }}
            ghcr.io/warjiang/kube-consul-register:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
